/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.redhat.leilaoejb;

/**
 * Home interface for LeilaoLegado.
 * @generated 
 * @wtp generated
 */
public interface LeilaoLegadoHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LeilaoLegado";
   public static final String JNDI_NAME="LeilaoLegado";

   public br.com.redhat.leilaoejb.LeilaoLegado create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
