/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.redhat.leilaoejb;

/**
 * Remote interface for LeilaoLegado.
 * @generated 
 * @wtp generated
 */
public interface LeilaoLegado
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String fazAlgumaCoisa(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public br.com.redhat.leilaoweb.dominio.entidade.Produto finalizarLeilao( br.com.redhat.leilaoweb.dominio.entidade.Produto produto )
      throws java.rmi.RemoteException;

}
